export const events = {
  toServer: {
    START_NEW_GAME: 'START_NEW_GAME',
    JOIN_THE_GAME: 'JOIN_THE_GAME',
    STROKE_TO_SERVER: 'STROKE_TO_SERVER',
    BACKGROUND_COLOR_TO_SERVER: 'BACKGROUND_COLOR_TO_SERVER',
    CLEAR_TO_SERVER: 'CLEAR_TO_SERVER',
  },
  fromServer: {
    ROOM_ID_FROM_SERVER: 'ROOM_ID_FROM_SERVER',
    INITIAL_PICTURE_FROM_SERVER: 'INITIAL_PICTURE_FROM_SERVER',
    STROKE_FROM_SERVER: 'STROKE_FROM_SERVER',
    BACKGROUND_COLOR_FROM_SERVER: 'BACKGROUND_COLOR_FROM_SERVER',
  },
};
